//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportDepot.CommissionsExecutor.CommissionsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceCommission", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    public partial class InvoiceCommission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TractorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIdField, value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceAmount {
            get {
                return this.InvoiceAmountField;
            }
            set {
                if ((this.InvoiceAmountField.Equals(value) != true)) {
                    this.InvoiceAmountField = value;
                    this.RaisePropertyChanged("InvoiceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Percent {
            get {
                return this.PercentField;
            }
            set {
                if ((this.PercentField.Equals(value) != true)) {
                    this.PercentField = value;
                    this.RaisePropertyChanged("Percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TractorId {
            get {
                return this.TractorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TractorIdField, value) != true)) {
                    this.TractorIdField = value;
                    this.RaisePropertyChanged("TractorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripNumber {
            get {
                return this.TripNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TripNumberField, value) != true)) {
                    this.TripNumberField = value;
                    this.RaisePropertyChanged("TripNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommissionRequest", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    public partial class CommissionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Span[] OffDutySpansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.TripSpan[] TripsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIdField, value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Span[] OffDutySpans {
            get {
                return this.OffDutySpansField;
            }
            set {
                if ((object.ReferenceEquals(this.OffDutySpansField, value) != true)) {
                    this.OffDutySpansField = value;
                    this.RaisePropertyChanged("OffDutySpans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.TripSpan[] Trips {
            get {
                return this.TripsField;
            }
            set {
                if ((object.ReferenceEquals(this.TripsField, value) != true)) {
                    this.TripsField = value;
                    this.RaisePropertyChanged("Trips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorType {
            get {
                return this.VendorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorTypeField, value) != true)) {
                    this.VendorTypeField = value;
                    this.RaisePropertyChanged("VendorType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Span", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TransportDepot.CommissionsExecutor.CommissionsReference.TripSpan))]
    public partial class Span : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Location EndLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Span PreviousSpanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Location StartLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TractorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Location EndLocation {
            get {
                return this.EndLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.EndLocationField, value) != true)) {
                    this.EndLocationField = value;
                    this.RaisePropertyChanged("EndLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Span PreviousSpan {
            get {
                return this.PreviousSpanField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousSpanField, value) != true)) {
                    this.PreviousSpanField = value;
                    this.RaisePropertyChanged("PreviousSpan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Location StartLocation {
            get {
                return this.StartLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StartLocationField, value) != true)) {
                    this.StartLocationField = value;
                    this.RaisePropertyChanged("StartLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TractorId {
            get {
                return this.TractorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TractorIdField, value) != true)) {
                    this.TractorIdField = value;
                    this.RaisePropertyChanged("TractorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TripSpan", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    public partial class TripSpan : TransportDepot.CommissionsExecutor.CommissionsReference.Span {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceAmoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Location TractorHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceAmout {
            get {
                return this.InvoiceAmoutField;
            }
            set {
                if ((this.InvoiceAmoutField.Equals(value) != true)) {
                    this.InvoiceAmoutField = value;
                    this.RaisePropertyChanged("InvoiceAmout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Location TractorHome {
            get {
                return this.TractorHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TractorHomeField, value) != true)) {
                    this.TractorHomeField = value;
                    this.RaisePropertyChanged("TractorHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripNumber {
            get {
                return this.TripNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TripNumberField, value) != true)) {
                    this.TripNumberField = value;
                    this.RaisePropertyChanged("TripNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommissionCandidate", Namespace="http://schemas.datacontract.org/2004/07/TransportDepot.Models.Payables.Commission" +
        "s")]
    [System.SerializableAttribute()]
    public partial class CommissionCandidate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Location EndLocatioinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportDepot.CommissionsExecutor.CommissionsReference.Location StartLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TractorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIdField, value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Location EndLocatioin {
            get {
                return this.EndLocatioinField;
            }
            set {
                if ((object.ReferenceEquals(this.EndLocatioinField, value) != true)) {
                    this.EndLocatioinField = value;
                    this.RaisePropertyChanged("EndLocatioin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceAmount {
            get {
                return this.InvoiceAmountField;
            }
            set {
                if ((this.InvoiceAmountField.Equals(value) != true)) {
                    this.InvoiceAmountField = value;
                    this.RaisePropertyChanged("InvoiceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportDepot.CommissionsExecutor.CommissionsReference.Location StartLocation {
            get {
                return this.StartLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StartLocationField, value) != true)) {
                    this.StartLocationField = value;
                    this.RaisePropertyChanged("StartLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TractorId {
            get {
                return this.TractorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TractorIdField, value) != true)) {
                    this.TractorIdField = value;
                    this.RaisePropertyChanged("TractorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripNumber {
            get {
                return this.TripNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TripNumberField, value) != true)) {
                    this.TripNumberField = value;
                    this.RaisePropertyChanged("TripNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.transportdepot.net/Payables", ConfigurationName="CommissionsReference.ICommissionService")]
    public interface ICommissionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.transportdepot.net/Payables/ICommissionService/GetAllCommissions", ReplyAction="http://www.transportdepot.net/Payables/ICommissionService/GetAllCommissionsRespon" +
            "se")]
        TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] GetAllCommissions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.transportdepot.net/Payables/ICommissionService/SaveCommissions", ReplyAction="http://www.transportdepot.net/Payables/ICommissionService/SaveCommissionsResponse" +
            "")]
        void SaveCommissions(TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] commissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.transportdepot.net/Payables/ICommissionService/GetCommissions", ReplyAction="http://www.transportdepot.net/Payables/ICommissionService/GetCommissionsResponse")]
        TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] GetCommissions(TransportDepot.CommissionsExecutor.CommissionsReference.CommissionRequest[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.transportdepot.net/Payables/ICommissionService/GetCandidates", ReplyAction="http://www.transportdepot.net/Payables/ICommissionService/GetCandidatesResponse")]
        TransportDepot.CommissionsExecutor.CommissionsReference.CommissionCandidate[] GetCandidates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.transportdepot.net/Payables/ICommissionService/SaveNewCommisions", ReplyAction="http://www.transportdepot.net/Payables/ICommissionService/SaveNewCommisionsRespon" +
            "se")]
        void SaveNewCommisions();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommissionServiceChannel : TransportDepot.CommissionsExecutor.CommissionsReference.ICommissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommissionServiceClient : System.ServiceModel.ClientBase<TransportDepot.CommissionsExecutor.CommissionsReference.ICommissionService>, TransportDepot.CommissionsExecutor.CommissionsReference.ICommissionService {
        
        public CommissionServiceClient() {
        }
        
        public CommissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] GetAllCommissions() {
            return base.Channel.GetAllCommissions();
        }
        
        public void SaveCommissions(TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] commissions) {
            base.Channel.SaveCommissions(commissions);
        }
        
        public TransportDepot.CommissionsExecutor.CommissionsReference.InvoiceCommission[] GetCommissions(TransportDepot.CommissionsExecutor.CommissionsReference.CommissionRequest[] request) {
            return base.Channel.GetCommissions(request);
        }
        
        public TransportDepot.CommissionsExecutor.CommissionsReference.CommissionCandidate[] GetCandidates() {
            return base.Channel.GetCandidates();
        }
        
        public void SaveNewCommisions() {
            base.Channel.SaveNewCommisions();
        }
    }
}
