
namespace TransportDepot.Data.Misc
{
  static class WorkaroundsQueries
  {
    public static string InsertTractors = @"
      INSERT INTO [dbo].[Tractor]
      (
             [T].[cTractorId]
          ,  [T].[cSerial]
          ,  [T].[cTitle]
          ,  [T].[bLessorTruck]
          ,  [T].[cLessorOwner]
          ,  [T].[bTractorAssigned]
          ,  [T].[cDriver]
          ,  [T].[cModel]
          ,  [T].[cType]
          ,  [T].[cMake]
          ,  [T].[cYear]
          ,  [T].[dDateBought]
          ,  [T].[cuCost]
          ,  [T].[cuFMV]
          ,  [T].[nlOdometerStart]
          ,  [T].[nlOdometerEnding]
          ,  [T].[bActive]
          ,  [T].[cComment]
          ,  [T].[cLocation]
          ,  [T].[cLicensePlate]
          ,  [T].[cInsuranceName]
          ,  [T].[cInsurancePolicy]
          ,  [T].[cWeight]
          ,  [T].[cHeight]
          ,  [T].[bScheduleToMaintenance]
          ,  [T].[cTripNumber]
          ,  [T].[cLastRecordedCity]
          ,  [T].[cLastRecordedState]
          ,  [T].[dLastRecordedDateTime]
          ,  [T].[cTireSize]
          ,  [T].[dInspectionDate]
      )
      SELECT
             [T].[cTractorId]
          ,  [T].[cSerial]
          ,  [T].[cTitle]
          ,  [T].[bLessorTruck]
          ,  [T].[cLessorOwner]
          ,  [T].[bTractorAssigned]
          ,  [T].[cDriver]
          ,  [T].[cModel]
          ,  [T].[cType]
          ,  [T].[cMake]
          ,  [T].[cYear]
          ,  [T].[dDateBought]
          ,  [T].[cuCost]
          ,  [T].[cuFMV]
          ,  [T].[nlOdometerStart]
          ,  [T].[nlOdometerEnding]
          ,  [T].[bActive]
          ,  [T].[cComment]
          ,  [T].[cLocation]
          ,  [T].[cLicensePlate]
          ,  [T].[cInsuranceName]
          ,  [T].[cInsurancePolicy]
          ,  [T].[cWeight]
          ,  [T].[cHeight]
          ,  [T].[bScheduleToMaintenance]
          ,  [T].[cTripNumber]
          ,  [T].[cLastRecordedCity]
          ,  [T].[cLastRecordedState]
          ,  [T].[dLastRecordedDateTime]
          ,  [T].[cTireSize]
          ,  [T].[dInspectionDate]
      FROM [dbo].[TractorBackup] T
    ";

    public static string InsertEmployees = @"
      INSERT INTO [dbo].[PrEmployee]
      (
            [cEmployeeId]
          , [cGroup]
          , [cSSN]
          , [cMaritalStatus]
          , [cFirst]
          , [cMiddle]
          , [cLast]
          , [cAddress]
          , [cCity]
          , [cState]
          , [cZip]
          , [cHomePhone]
          , [cCellularPager]
          , [dDateHired]
          , [dDateTerminated]
          , [bActive]
          , [bIncludeInPayroll]
          , [bIncludeInDriverList]
          , [dDateOfBirth]
          , [mEmergency]
          , [mOtherComment]
          , [niPayPeriodPerYear]
          , [bExemptFedUnEmp]
          , [bExemptIncomeTaxWH]
          , [bFICAss]
          , [bFICAMedicare]
          , [cuAdditionalFedWH]
          , [cUnEmpTaxState]
          , [mAdditionalInformation]
          , [bStatutory]
          , [bDeceased]
          , [bPensionPlan]
          , [bLegalRep]
          , [bDeferredCompensation]
          , [niFedExempt]
          , [cFedTable]
          , [cStCode1]
          , [niStExempt1]
          , [cStTable1]
      )

      SELECT 
            [cEmployeeId]
          , [cGroup]
          , [cSSN]
          , [cMaritalStatus]
          , [cFirst]
          , [cMiddle]
          , [cLast]
          , [cAddress]
          , [cCity]
          , [cState]
          , [cZip]
          , [cHomePhone]
          , [cCellularPager]
          , [dDateHired]
          , [dDateTerminated]
          , [bActive]
          , [bIncludeInPayroll]
          , [bIncludeInDriverList]
          , [dDateOfBirth]
          , [mEmergency]
          , [mOtherComment]
          , [niPayPeriodPerYear]
          , [bExemptFedUnEmp]
          , [bExemptIncomeTaxWH]
          , [bFICAss]
          , [bFICAMedicare]
          , [cuAdditionalFedWH]
          , [cUnEmpTaxState]
          , [mAdditionalInformation]
          , [bStatutory]
          , [bDeceased]
          , [bPensionPlan]
          , [bLegalRep]
          , [bDeferredCompensation]
          , [niFedExempt]
          , [cFedTable]
          , [cStCode1]
          , [niStExempt1]
          , [cStTable1]
      FROM [dbo].[PrEmployeeBackup]
    ";

    public static string InsertBillingHistory = @"
      INSERT INTO [Trans].[dbo].[BillingHistory]
      (
            [nlOrderNumber]
          , [cDispatcherInit]
          , [cBOL]
          , [cTripnumber]
          , [cPronumber]
          , [bAssigned]
          , [bFinishTrip]
          , [dTripFinishDate]
          , [dBillDate]
          , [bPosted]
          , [cCustomerID]
          , [dCallerDate]
          , [cloadDescriptionCode]
          , [cOrigID]
          , [cOrigName]
          , [cOrigAddress]
          , [cOrigCity]
          , [cOrigState]
          , [cOrigZip]
          , [cOrigTel]
          , [dShipDate]
          , [cDestID]
          , [cDestName]
          , [cDestAddress]
          , [cDestCity]
          , [cDestState]
          , [cDestZip]
          , [cDestTel]
          , [dDeliveryDate]
          , [mTripInstruction]
          , [bSplit]
          , [cPONumber]
          , [mTempDirections1]
          , [mTempDirections2]
          , [mTempDirections3]
          , [cCustomerPU]
          , [bPrintout]
          , [cuSplitRevenue]
          , [bPrevReversed]
          , [cConsPronumber]
          , [cCustomerRef]
          , [cBillComment]
          , [cTempName]
          , [bPartialLoad]
          , [nbOrigPalletsIn]
          , [nbOrigPalletsOut]
          , [nbDestPalletsIn]
          , [nbDestPalletsOut]
          , [cCustomsBroker]
          , [niPriority]
          , [bPaperworkReceived]
          , [dPaperworkDate]
          , [bClaimsPending]
          , [bShipperNet]
          , [cSNImportID]
          , [nlSNImportOrder]
          , [cSNImportOffice]
          , [cSalesPersonInit]
          , [bBobtail]
          , [cCompleteInit]
          , [bUnloaded]
          , [dUnloadedDate]
          , [bDoNotPost]
      )
      SELECT
            [nlOrderNumber]
          , [cDispatcherInit]
          , [cBOL]
          , [cTripnumber]
          , [cPronumber]
          , [bAssigned]
          , [bFinishTrip]
          , [dTripFinishDate]
          , [dBillDate]
          , [bPosted]
          , [cCustomerID]
          , [dCallerDate]
          , [cloadDescriptionCode]
          , [cOrigID]
          , [cOrigName]
          , [cOrigAddress]
          , [cOrigCity]
          , [cOrigState]
          , [cOrigZip]
          , [cOrigTel]
          , [dShipDate]
          , [cDestID]
          , [cDestName]
          , [cDestAddress]
          , [cDestCity]
          , [cDestState]
          , [cDestZip]
          , [cDestTel]
          , [dDeliveryDate]
          , [mTripInstruction]
          , [bSplit]
          , [cPONumber]
          , [mTempDirections1]
          , [mTempDirections2]
          , [mTempDirections3]
          , [cCustomerPU]
          , [bPrintout]
          , [cuSplitRevenue]
          , [bPrevReversed]
          , [cConsPronumber]
          , [cCustomerRef]
          , [cBillComment]
          , [cTempName]
          , [bPartialLoad]
          , [nbOrigPalletsIn]
          , [nbOrigPalletsOut]
          , [nbDestPalletsIn]
          , [nbDestPalletsOut]
          , [cCustomsBroker]
          , [niPriority]
          , [bPaperworkReceived]
          , [dPaperworkDate]
          , [bClaimsPending]
          , [bShipperNet]
          , [cSNImportID]
          , [nlSNImportOrder]
          , [cSNImportOffice]
          , [cSalesPersonInit]
          , [bBobtail]
          , [cCompleteInit]
          , [bUnloaded]
          , [dUnloadedDate]
          , [bDoNotPost]
      FROM [dbo].[BillingHistoryBackup]
    ";

    public static string InsertArEntry = @"
      INSERT INTO [Trans].[dbo].[ArEntry]
      (
	        [cCustomerId]
          , [cPronumber]
          , [cuAmount]
          , [bFullyPaid]
          , [dDateOfInvoice]
          , [cArAcct]
          , [cTripNumber]
          , [bCanadianFunds]
          , [cShipperRef]
          , [nlOrderNumber]
          , [bPrepaid]
          , [cuCrntPymtAmt]
          , [dCrntPymtDate]
          , [cCrntCheckNo]
          , [cuBalanceDue]
      )
	      SELECT 
	        [AE].[cCustomerId]
          , [AE].[cPronumber]
          , [AE].[cuAmount]
          , [AE].[bFullyPaid]
          , [AE].[dDateOfInvoice]
          , [AE].[cArAcct]
          , [AE].[cTripNumber]
          , [AE].[bCanadianFunds]
          , [AE].[cShipperRef]
          , [AE].[nlOrderNumber]
          , [AE].[bPrepaid]
          , [AE].[cuCrntPymtAmt]
          , [AE].[dCrntPymtDate]
          , [AE].[cCrntCheckNo]
          , [AE].[cuBalanceDue]

      FROM  [dbo].[ArEntryBackup] [AE]
    ";

    public static string BackupTable = @"
      IF OBJECT_ID('dbo.{0}Backup', 'U') IS NOT NULL 
        DROP TABLE [dbo].[{0}Backup]; 
      SELECT * INTO [dbo].[{0}Backup] FROM [dbo].[{0}]
  ";
  }
}
